<?php
$ZH = array(
	'title'			=>  '天津谱祥伟业科技',
	'Home'			=>	'首页',
	'Products'		=>	'产品介绍',
	'News'			=>	'新闻动态',
	'Service'		=>	'用户服务',
	'Partners'		=>	'合作伙伴',
	'Career'		=>	'招贤纳士',
	'Contact'		=>	'联系我们',

	'wel_title' 	=> '欢迎来到谱祥伟业',
	'wel_brief' 	=> '天津谱祥伟业科技有限公司系集产品开发、生产、施工为一体的高新技术企业。仪器部代理多种国外实验室仪器、高效液相和气相色谱仪器、紫外扫描分光光度计及相关配件耗材等。公司自行设计生产的实验室仪器设备：氨基酸分析仪、示差折光检测器、蒸发光散射检测器、集菌仪、多联过滤器、柱温箱、超声波清洗机及色谱柱、葡聚糖凝胶色谱柱G10、通用保护住、液相色谱柱。',
	'wel_content_1'	=> '我们不但为您提供优质的产品更为您提供优质的技术服务。当您需要性能价格最好的色谱产品，当您遇到技术困难，请和我们联系。',
	'wel_content_2'	=> '',
	'pros_title'	=> '产品展示',
	'pros_content'	=> '',
	'news_title'	=> '最新动态',
	'news_more'		=> '更多新闻',
	'contact_title'	=> '联系我们',
	'company_name'	=> '公司名称',
	'company_add'	=> '公司地址',
	'company_zip'	=> '公司邮编',
	'company_tel'	=> '公司电话',
	'company_fax'	=> '公司传真',
	'company_mail'	=> '电子邮件',
	'ft_link'		=> '友情链接',
	'ft_msg'		=> '产品介绍',
	'ft_partner'	=> '新闻动态',
	'ft_join'		=> '加入我们',
	'ft_icp'		=> '备案号',
	'recruit_num'	=> '序列号',
	'recruit_post'	=> '招聘职位',
	'recruit_date'	=> '发表日期',
	'recruit_person'=> '招聘人数',
	'recruit_more'	=> '更多',

	'recruit_btn_1' => '查看详情',
	'recruit_btn_2' => '申请职位',

	'mesg_title'    =>'在线留言',
	'mesg_holde1'	=>'主题',
	'mesg_holde2'	=>'姓名',
	'mesg_holde3'	=>'邮箱',
	'mesg_holde4'	=>'地址',
	'mesg_holde5'	=>'公司',
	'mesg_holde6'	=>'电话',
	'mesg_holde7'	=>'反馈信息',
	'mesg_holde8'	=>'确定',
	'mesg_sus'		=>'操作成功',
	'mesg_sthk'		=>'感谢您的留言!!',
	'mesg_err'		=>'操作失败  !',
	'mesg_ethk'		=>'出错了...',
	'mesg_yz1'		=>'请输入您的姓名·邮箱·主题·留言内容,我们会及时对您答复!',
	'mesg_yz2'		=>'请输入您的姓名！',
	'mesg_yz3'		=>'请输入您的邮箱！',
	'mesg_yz4'		=>'请输入您的留言内容！',

	'new'			=>'新闻动态',
	'new_title1'  	=>'公司动态',
	'new_title2'  	=>'知识百问',
	'new_title3'  	=>'促销信息',
	'new_time'  	=>'发布时间',
	'new_person'  	=>'发布人',
	'new_pname'  	=>'天津谱祥伟业科技',
	'new_clicks'  	=>'点击量',
	'new_search'	=>'产品搜索',
	'new_xiaox'		=>'搜索',
	'new_xiaox1'	=>'共',
	'new_xiaox2'	=>'条记录',
	'new_sp'		=>'请输入关键字',

	'career'		=> '招贤纳士',

	'career_apply'	=> '应聘职位',

	'app_name'		=> '姓名',
	'app_sex'		=> '性别',
	'app_age'		=> '年龄',
	'app_birthplace'=> '籍贯',
	'app_nation'	=> '民族',
	'app_education'	=> '学历',
	'app_political'	=> '政治面貌',
	'app_g_date'	=> '毕业日期',
	'app_marriage'	=> '婚姻状况',
	'app_school'	=> '毕业院校',
	'app_qualification'	=> '所学专业',
	'app_lan' 		=> '英语水平',
	'app_phone' 	=> '联系电话',
	'app_residence' => '户口所在地',
	'app_position'  => '应聘职位',
	'app_skills'  	=> '其他技能',
	'app_address'  	=> '家庭住址',
	'app_exp'	  	=> '实习/实践经历',
	'app_awards'	=> '在校期间参加活动、培训和获得奖励及证书情况',
	'app_fun'		=> '个人特长、兴趣爱好',
	'app_btn'		=> '提交',

	'Cooperation'	=>'合作伙伴',
	'tel'			=>'公司电话',
	'mail'			=>'电子邮件',
	'Company'		=>'联系我们',
	'CompanyName'	=>'公司名称',
	'CompanyAddress'=>'公司地址',
	'CompanyZip'	=>'公司邮编',
	'CompanyFax'	=>'公司传真',
	'QQ Online consulting'=>'QQ在线咨询',
	'WeChat'=>'扫描微信二维码',
	'Add attention'=>'添加关注',
);
$EN = array(
	'title'			=>  'PuXiangWeiYe',
	'Home'			=>	'Home',
	'Products'		=>	'Products',
	'News'			=>	'News',
	'Service'		=>	'Service',
	'Partners'		=>	'Partners',
	'Career'		=>	'Career',
	'Contact'		=>	'Contact',

	'wel_title' 	=> 'Welcome to Pu Xiang Wei Ye',
	'wel_brief'	=> 'Tianjin Pu Xiang Wei Ye is department of product development, production and construction of high-tech enterprises. As part of agent of many foreign laboratories equipment, high performance liquid chromatography and gas chromatography equipment, UV scanning spectrophotometers and related accessories. Company\'s own design and production of laboratory equipment: amino acid Analyzer, refractive index detectors, evaporative light scattering detectors, collecting bacteria detector, multiple filters, column oven, ultrasonic cleaning machines and chromatographic column, sephadex gel chromatography column G10, general protection, liquid chromatography.',
	'wel_content_1'	=> 'We not only provide you with the highest quality products provide you with quality services. When you need to best price performance of chromatography products, when you encounter technical difficulties, please contact us.',
	'wel_content_2'	=> '',
	'pros_title'	=> 'PRODUCT DISPLAY',
	'pros_content'	=> '',
	'news_title'	=> 'COMPANY NEWS',
	'news_more'		=> 'more...',
	'contact_title'	=> 'CONTACT US',
	'company_name'	=> 'Company',
	'company_add'	=> 'Add',
	'company_zip'	=> 'Zip',
	'company_tel'	=> 'Tel',
	'company_fax'	=> 'Fax',
	'company_mail'	=> 'Email',
	'ft_link'		=> 'Links',
	'ft_msg'		=> 'Pros',
	'ft_partner'	=> 'News',
	'ft_join'		=> 'Join Us',
	'ft_icp'		=> 'ICP',
	'recruit_num'	=> 'No.',
	'recruit_post'	=> 'Position',
	'recruit_date'	=> 'Date',
	'recruit_person'=> 'Persons',
	'recruit_more'	=> 'More',

	'recruit_btn_1' => 'Detail',
	'recruit_btn_2' => 'Apply',

	'mesg_title'    =>'Online Message',
	'mesg_holde1'	=>'theme',
	'mesg_holde2'	=>'name ',
	'mesg_holde3'	=>'email address',
	'mesg_holde4'	=>'address',
	'mesg_holde5'	=>'company',
	'mesg_holde6'	=>'phone',
	'mesg_holde7'	=>'feedback information',
	'mesg_holde8'	=>'OK',
	'mesg_sus'		=>'This operation succeeds.',
	'mesg_sthk'		=>'Thank you for your messages!',
	'mesg_err'		=>'Operation Failed !',
	'mesg_ethk'		=>'Error...',
	'mesg_yz1'		=>'Please enter your name·email·subject·the message content, we will reply to you in time！',
	'mesg_yz2'		=>'Please enter your name！',
	'mesg_yz3'		=>'Please enter your email！',
	'mesg_yz4'		=>'Please enter your message content！',

	'new'			=>'News',
	'new_title1'  	=>'CompanyNews',
	'new_title2'  	=>'Encyclopedia',
	'new_title3'  	=>'Promotions',
	'new_time'  	=>'release time',
	'new_person'  	=>'promulgator',
	'new_pname'  	=>'tianjinpuxiangweiye',
	'new_clicks'  	=>'hits',
	'new_search'	=>'Product search',
	'new_xiaox'		=>'Search for',
	'new_xiaox1'	=>'a total of',
	'new_xiaox2'	=>'records',
	'new_sp'		=>'Please enter the keywords',



	'career'		=> 'Career',

	'career_apply'	=> 'Position',

	'app_name'		=> 'Name',
	'app_sex'		=> 'Sex',
	'app_age'		=> 'Age',
	'app_birthplace'=> 'Birthplace',
	'app_nation'	=> 'Nation',
	'app_education'	=> 'Education',
	'app_political'	=> 'Political',
	'app_g_date'	=> 'Graduation Date',
	'app_marriage'	=> 'Marriage',
	'app_school'	=> 'School',
	'app_qualification'	=> 'Qualification',
	'app_lan' 		=> 'Language Proficiency',
	'app_phone' 	=> 'Phone',
	'app_residence' => 'Registered Residence',
	'app_position'  => 'Position',
	'app_skills'  	=> 'Skills',
	'app_address'  	=> 'Address',
	'app_exp'	  	=> 'Work Experience',
	'app_awards'	=> 'Awards and Certificates',
	'app_fun'		=> 'Strengths Hhobbies',
	'app_btn'		=> 'Submit',

	'Cooperation'   => 'Cooperative partner',
	'tel'			=>'CompanyTel',
	'mail'			=>'E-Mail',
	'Company'		=>'Contact Us',
	'CompanyName'	=>'CompanyName',
	'CompanyAddress'=>'CompanyAddress',
	'CompanyZip'	=>'CompanyZip',
	'CompanyFax'	=>'CompanyFax',
	'QQ Online consulting'=>'QQ Online consulting',
	'WeChat'=>'WeChat',
	'Add attention'=>'Add attention',
);
return array(
	'KMC_language'	=>	array(
		'ZH' => $ZH,
		'EN' => $EN,
	)
);


